"""Transparency label generation. Turns a verdict + confidence into reader-facing
plain-language text. Confidence is communicated as a strength word and a
percentage, never a bare decimal. See planning.md §3 and the README for the
verbatim variants.
"""


def _strength_word(confidence):
    if confidence >= 0.85:
        return "strong"
    if confidence >= 0.70:
        return "moderate"
    return "low"


def build_label(verdict, confidence):
    """Return {'variant', 'headline', 'body', 'text'} for display to a reader."""
    pct = round(confidence * 100)
    strength = _strength_word(confidence)

    if verdict == "ai":
        headline = "🤖 Likely AI-generated."
        body = f"Our analysis suggests this piece was probably created with the help of generative AI ({strength} confidence, {pct}%). This is an automated estimate, not a certainty, and the creator can appeal this decision."
        variant = "high-confidence-ai"
    elif verdict == "human":
        headline = "✍️ Likely human-written."
        body = f"Our analysis found no strong signs of AI generation in this piece ({strength} confidence, {pct}%). This is an automated estimate, not a guarantee of authorship."
        variant = "high-confidence-human"
    else:
        headline = "🔍 Not enough signal to call."
        body = f"Our analysis couldn't confidently determine whether this piece was written by a human or generated by AI (low confidence, {pct}%). We're showing this honestly rather than guessing. No attribution claim is being made."
        variant = "uncertain"

    return {
        "variant": variant,
        "headline": headline,
        "body": body,
        "text": f"{headline} {body}",
    }
