"""Signal 1 — LLM classification via Groq (llama-3.3-70b-versatile).

Reads the text holistically the way a careful human reader would and estimates
the probability it was AI-generated. This captures semantic/stylistic coherence
that the structural stylometry signal is blind to.

If Groq is unavailable (no key, network error, quota, bad JSON) we return a
graceful "unavailable" result so the pipeline can fall back to stylometry alone.

Blind spots (planning.md §1): it is itself a probabilistic guess, biased against
non-native / very formal prose, and fooled by lightly human-edited AI text.
"""

import json
import os

MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are a forensic text analyst. You assess whether a piece of writing was "
    "generated by an AI language model or written by a human. Consider voice, "
    "idiosyncrasy, imagery, tonal evenness, and word choice. AI text tends to be "
    "tonally even, generic, and 'safe'; human writing carries voice, surprising "
    "choices, and rough edges. You must remain cautious: do not accuse a human "
    "without strong evidence. Respond ONLY with a JSON object of the form "
    '{"p_ai": <float 0..1>, "rationale": "<one sentence>"} where p_ai is your '
    "estimated probability the text is AI-generated."
)


def _clip01(x):
    try:
        return max(0.0, min(1.0, float(x)))
    except (TypeError, ValueError):
        return 0.5


def classify(text):
    """Return {'p_ai': float, 'rationale': str, 'available': bool}."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return {
            "p_ai": 0.5,
            "rationale": "LLM signal unavailable: GROQ_API_KEY not set.",
            "available": False,
        }

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            max_tokens=200,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        return {
            "p_ai": _clip01(data.get("p_ai", 0.5)),
            "rationale": str(data.get("rationale", ""))[:300],
            "available": True,
        }
    except Exception as exc:  # noqa: BLE001 — degrade gracefully on any failure
        return {
            "p_ai": 0.5,
            "rationale": f"LLM signal unavailable: {type(exc).__name__}.",
            "available": False,
        }
